### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by FyberOptic** [MinecraftForkage/MinecraftForkage#1]
It's certainly a good attempt so far, but I wanted to point out some things.

One thing you might want to mention in the build instructions is that in order to run 'git submodule update --init --recursive' they need to setup their SSH private key and add it to their Github account or it fails.

Second, the Eclipse project for Fernflower's src directory isn't relative to the project directory, it was to a path on your machine.  I had to manually fix that.  

Third, I just plain couldn't get it to patch.  I tried literally ten times, and another time after opening this just for the benefit of the doubt.  Perhaps luck just wasn't on my side.  That aspect is the project's Achilles' heel at the moment for me, although I realize from my own work just what a problem it can be trying to create a patch for decompiled code, and can imagine what a nightmare that would be for as much stuff as Forge patches (way too much, IMO).  I'm not sure of the exact build process here, but I would suggest maybe trying to patch each file individually, and if it fails, you decompile just that class again, run the source through whatever processing it goes through, and try to patch again, until it hopefully works.

**Comment by immibis** [comment]
This Fernflower fix should make patching work every time.

The eclipse workspace update should fix the Fernflower src directory as well.
