### ISSUE TITLE
trying to add NotEnoughIDs still have problem

### ISSUE THREAD

**Issue by lightning02** [MinecraftForkage/MinecraftForkage#10]
with your mod the crash of maximum id reached does not occurr but when i try to generate a new world the game crash.
i've add both not enough ids and not enough ids-ttweaker, even downloading fastcraft 1.22 c17.
did i miss something? what could i do to make it works?
[crash-2015-12-18_22.11.50-server.txt](https://github.com/MinecraftForkage/MinecraftForkage/files/67192/crash-2015-12-18_22.11.50-server.txt)

**Comment by Solarstrike** [comment]
Update your NEID version to 1.4.0.

**Comment by immibis** [comment]
This isn't Not Enough IDs.

**Comment by lightning02** [comment]
NEID is already version 1.4.0.
I Really appreciated what the owner of this mod did with Not Enough Ids, it's like the dream of every one that want to have fun with all of his/her favourite mods i wonder why forge developers didn't do this. I guess than that it is a great resposability and work to develop and mantain a such good mod like this, that's why i controlled if i was missing something before post the issue and that's why the version of the mod i used it's already 1.4.0. Anyway since i'm a human and could fail i may still miss something. (that's why i'm here to asking for help)

**Comment by lightning02** [comment]
and also the neid tweaker I guess is last version too

**Comment by walkerjonny** [comment]
Remove neid tweaker. It is not required anymore with neid 1.4.0.

**Comment by lightning02** [comment]
I've add neid tweaker after beacuse just with neid the world was going crash

**Comment by walkerjonny** [comment]
This is definitively so. Read the Changed post for NEID 1.4.0.
http://www.curse.com/mc-mods/minecraft/235107-notenoughids#t1:changes.
http://minecraft.curseforge.com/projects/notenoughids/files/2266877
Do you really have NEID 1.4.0 installed together with Fastcraft 1.22_ctest17?

**Comment by lightning02** [comment]
Yes I do, that's why I'm posting the issue here, I would really like to figure out the problem but I'm not so good at reading java and crash report :/
http://i.imgur.com/dNY9dlb.png
http://i.imgur.com/U22M7nW.png
removing NEID tweaker the pack doesen't even start now, the crash report is this
[crash-2015-12-20_15.32.30-client.txt](https://github.com/MinecraftForkage/MinecraftForkage/files/67825/crash-2015-12-20_15.32.30-client.txt)

and this is the latest log
http://pastebin.com/vbUG1FiZ

 also tryed to remove fastcraft completely from the modpack, without results
